// General
module.exports.GENERAL = {
    DATABASE: "DATABASE_ERROR",
    FORM_DATA: "FORM_DATA_ERROR",
    BOT_REQUEST: "BOT_REQUEST_ERROR",
    PICTURE_TYPE: "BAD_PICTURE_TYPE_ERROR",
};

// Middleware
module.exports.MIDDLEWARE = {
    INVALID_TOKEN: "INVALID_TOKEN_ERROR",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    NO_PERMISSIONS: "NO_PERMISSIONS_ERROR",
    UNAUTHORIZED_REQUEST: "UNAUTHORIZED_REQUEST_ERROR",
};

// Users
module.exports.USERS = {
    USER_AUTH: "USER_AUTH_ERROR",
    USER_TOKEN: "USER_TOKEN_NOT_FOUND",
    USER_DISABLED: "USER_DISABLED_ERROR",
    NOT_FOUND_BY_USERNAME: "USER_NOT_FOUND_BY_USERNAME",
};

// Token
module.exports.TOKENS = {
    TOKEN_UPDATE: "TOKEN_UPDATE_ERROR",
};

