// General
module.exports.GENERAL = {
    DATABASE: "DATABASE_ERROR",
    FORM_DATA: "FORM_DATA_ERROR",
    NO_CHANGES: "NO_CHANGES_ERROR",
    BOT_REQUEST: "BOT_REQUEST_ERROR",
    CLOUD_SERVICE: "CLOUD_SERVICE_ERROR",
    PICTURE_TYPE: "BAD_PICTURE_TYPE_ERROR",
    HIGH_LEVEL_DATA: "HIGH_LEVEL_DATA_ERROR",
};

// Middleware
module.exports.MIDDLEWARE = {
    INVALID_TOKEN: "INVALID_TOKEN_ERROR",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    NO_PERMISSIONS: "NO_PERMISSIONS_ERROR",
    UNAUTHORIZED_REQUEST: "UNAUTHORIZED_REQUEST_ERROR",
};

// Roles
module.exports.ROLES = {
    ROLE_NOT_FOUND: "ROLE_NOT_FOUND_ERROR",
};

// Users
module.exports.USERS = {
    USER_AUTH: "USER_AUTH_ERROR",
    USER_UPDATE: "USER_UPDATE_ERROR",
    USER_DELETE: "USER_DELETE_ERROR",
    CREATE_USER: "CREATE_USER_ERROR",
    USER_DISABLED: "USER_DISABLED_ERROR",
    USER_NOT_FOUND: "USER_NOT_FOUND_ERROR",
    USER_TOKEN: "USER_TOKEN_NOT_FOUND_ERROR",
    SAME_PASSWORD: "USER_HAS_SAME_PASSWORD_ERROR",
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST_ERROR",
    PASSWORD_NOT_MATCH: "USER_PASSWORD_NOT_MATCH_ERROR",
    USER_PROPERTIES_UPDATE: "USER_PROPERTIES_UPDATE_ERROR",
};

// Properties
module.exports.PROPERTIES = {
    PROPERTY_UPDATE: "PROPERTY_UPDATE_ERROR",
    PROPERTY_DELETE: "PROPERTY_DELETE_ERROR",
    PROPERTY_CREATE: "PROPERTY_CREATE_ERROR",
    PROPERTY_NOT_FOUND: "PROPERTY_NOT_FOUND_ERROR",
};

// Goods
module.exports.GOODS = {
    GOOD_UPDATE: "GOOD_UPDATE_ERROR",
    GOOD_DELETE: "GOOD_DELETE_ERROR",
    GOOD_CREATE: "GOOD_CREATE_ERROR",
    GOOD_NOT_FOUND: "GOOD_NOT_FOUND_ERROR",
    WRONG_GOOD_COLOR: "WRONG_GOOD_COLOR_ERROR"
};

// Chambers
module.exports.CHAMBERS = {
    CHAMBER_UPDATE: "CHAMBER_UPDATE_ERROR",
    CHAMBER_CREATE: "CHAMBER_CREATE_ERROR",
    CHAMBER_DELETE: "CHAMBER_DELETE_ERROR",
    CHAMBER_NOT_FOUND: "CHAMBER_NOT_FOUND_ERROR",
    WRONG_CHAMBER_TYPE: "WRONG_CHAMBER_TYPE_ERROR",
    WRONG_CHAMBER_RENT: "WRONG_CHAMBER_RENT_ERROR",
    WRONG_CHAMBER_PROPERTY: "WRONG_CHAMBER_PROPERTY_ERROR",
};

// Leases
module.exports.LEASES = {
    LEASE_UPDATE: "LEASE_UPDATE_ERROR",
    CREATE_LEASE: "CREATE_LEASE_ERROR",
    LEASE_NOT_FOUND: "LEASE_NOT_FOUND_ERROR",
    RENT_PERIOD_TOO_BIG: "RENT_PERIOD_TOO_BIG",
    WRONG_LEASE_RENT: "WRONG_LEASE_RENT_ERROR",
    WRONG_RENT_PERIOD: "WRONG_RENT_PERIOD_ERROR",
    WRONG_LEASE_SURETY: "WRONG_LEASE_SURETY_ERROR",
    WRONG_LEASE_PERIOD: "WRONG_LEASE_PERIOD_ERROR",
    WRONG_LEASE_DEPOSIT: "WRONG_LEASE_DEPOSIT_ERROR",
};


